# Generated by Django 5.2.1 on 2025-05-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/img/default_user_img/default_user.png', upload_to='media/posts/'),
        ),
    ]
